openapi: 3.0.0
info:
  description: >-
    Solucionador de partidas de póker realizado por Carlos Núñez Arenas para
    ISADevDay 2021.
  version: 1.0.0
  title: Poker Solver
  contact:
    email: carnuare@gmail.com
tags:
  - name: hand
    description: Escoge el ganador
paths:
  /api/v1/hand:
    post:
      description: >-
        La entrada será un array con varias rondas. Cada ronda contiene un
        conjunto de jugadas a comparar (con un nombre de jugador, una apuesta, y
        cinco cartas -una mano- por jugada), y un bote acumulado por los empates
        anteriores, que ganará el jugador que mejor mano tenga.
      operationId: solvePoker
      responses:
        '200':
          description: Resultados
          content:
            plain/text:
              schema:
                type: string
                example: '["Neymar gana 31000 euros.","Verdadero empate.","Cristiano gana 42000 euros.","Partida amañada."]'
        '201':
          description: error
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
      requestBody:
        x-name: ArrayRondas
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArrayRondas'
components:
  schemas:
    errorModel:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    ArrayRondas:
      type: array
      description: Array con un varias rondas
      example:
        - jugadas:
          - jugador: Cristiano
            apuesta: 1000
            cartas:
            - valor: "2"
              palo: H
            - valor: "3"
              palo: D
            - valor: "5"
              palo: S
            - valor: "9"
              palo: C
            - valor: K
              palo: D
          - jugador: Neymar
            apuesta: 20000
            cartas:
            - valor: "2"
              palo: C
            - valor: "3"
              palo: H
            - valor: "4"
              palo: S
            - valor: "8"
              palo: C
            - valor: A
              palo: H
          bote: "10000"
        - jugadas:
          - jugador: Cristiano
            apuesta: 1000
            cartas:
            - valor: "2"
              palo: H
            - valor: "3"
              palo: D
            - valor: "5"
              palo: S
            - valor: "9"
              palo: C
            - valor: K
              palo: D
          - jugador: Neymar
            apuesta: 20000
            cartas:
            - valor: "2"
              palo: D
            - valor: "3"
              palo: H
            - valor: "5"
              palo: C
            - valor: "9"
              palo: S
            - valor: K
              palo: H
          bote: 0
        - jugadas:
          - jugador: Cristiano
            apuesta: 1000
            cartas:
            - valor: "2"
              palo: H
            - valor: "4"
              palo: S
            - valor: "4"
              palo: C
            - valor: "2"
              palo: D
            - valor: "4"
              palo: H
          - jugador: Neymar
            apuesta: 20000
            cartas:
            - valor: "2"
              palo: S
            - valor: "8"
              palo: S
            - valor: A
              palo: S
            - valor: Q
              palo: S
            - valor: "3"
              palo: S
          bote: 21000
        - jugadas:
          - jugador: Cristiano
            apuesta: 1000
            cartas:
            - valor: "2"
              palo: H
            - valor: "3"
              palo: D
            - valor: "5"
              palo: S
            - valor: "9"
              palo: C
            - valor: K
              palo: D
          - jugador: Neymar
            apuesta: 20000
            cartas:
            - valor: "2"
              palo: C
            - valor: "3"
              palo: H
            - valor: "4"
              palo: S
            - valor: "8"
              palo: C
            - valor: K
              palo: H
          - jugador: Maradona
            apuesta: 40000
            cartas:
            - valor: "2"
              palo: H
            - valor: "4"
              palo: D
            - valor: "3"
              palo: S
            - valor: "7"
              palo: C
            - valor: A
              palo: D
          bote: 0
      items:
        $ref: '#/components/schemas/Ronda'
    Ronda:
      type: object
      properties:
        jugadas:
          minItems: 2
          type: array
          items:
            type: object
            properties:
              jugador:
                type: string
              apuesta:
                type: integer
                format: int32
              cartas:
                type: array
                minItems: 5
                maxItems: 5
                items:
                  type: object
                  properties:
                    valor:
                      type: string
                    palo:
                      type: string
        bote:
          type: integer

