name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      input_text:
        required: true
        default: 'Ejemplo'
      num_of_repeats:
        required: false
        default: '1'

jobs:
  sample_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/js-repeat.yml
 
			- name: Print JavaScript output
				run: echo ${{ steps.js-action.outputs.output_text }}