name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        default: 'Mona the Octocat'
      status:
        description: 'Status'
        required: false

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- status: ${{ github.event.inputs.status }}!"