name: new-manual-actions
on:
  workflow_dispatch:
      inputs:
        input_text:
          required: true
          default: 'Ejemplo'
        num_of_repeats:
          required: false
          default: '1'
jobs:
  run-js:
    runs-on: ubuntu-latest
    outputs:
      output-text:
    steps:
      - name: js repeat 
        id: js-action
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install @actions/core
      - run: node ./js/action.js
      - run: echo ${{ steps.js-action.outputs.output_text }}